#!/usr/bin/env bash
set -euo pipefail

dry_run=
if test -n "$GIT_PUSH_OPTION_COUNT"; then
  i=0
  while test "$i" -lt "$GIT_PUSH_OPTION_COUNT"; do
    eval "value=\$GIT_PUSH_OPTION_$i"
    case "$value" in
    dry-run)
      dry_run=x
      ;;
    esac
    i=$((i + 1))
  done
fi

if test -n "$dry_run"; then
  unset python
  . ./hooks/env
  if [ -z "${python+x}" ]; then
    echo "ERROR: variable 'python' not set" >&2
    exit 1
  fi
  if [ -z "$python" ]; then
    echo "ERROR: variable 'python' is set to an empty value" >&2
    exit 1
  fi
  if ! command -v -- "$python" >/dev/null 2>&1; then
    echo "ERROR: '$python' is not a valid python executable" >&2
    exit 1
  fi

  $python "hooks/pre-receive.py" --dry-run
  exit 1
fi
